version: '3.6'
services:
  ghidra-server:
    image: infrid/ghidra-server
    # Ghidra needs to know where the connections are coming from,
    # hence we need to specify the hostname. This value will be also
    # used in the server.conf for the -ip arg.
    hostname: somehost.test
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghidra-server
    env_file:
      - '.env'
    ports:
      - '13100:13100'
      - '13101:13101'
      - '13102:13102'
    volumes:
      # You want your data to be persistent, let's mount some
      # directories
      - "./volumes/repo:/srv/repositories:"
      - "./volumes/cert:$GHIDRA_CERT_PATH:"
    restart: unless-stopped

