version: '3.6'
services:
  ghidra-server:
    image: ghidra/server
    build:
      context: ./ghidra/
      dockerfile: Dockerfile
    container_name: ghidra-server
    hostname: 'ghidra.infrid.test'
    environment:
      - TERM=xterm-256color
    ports:
      - '13100:13100'
      - '13101:13101'
      - '13102:13102'
    volumes:
      - './volumes/repo:/srv/repositories:'
    networks:
      - ghidra-server
    restart: unless-stopped

networks:
  ghidra-server: